const participants_names = {
    'alifbintujo' : 'Md. Alif Bin Turjo',
    'aaban_saad' : 'Aaban Saad',
    'AiFardin' : 'Aminul Islam',
    'talha_muammar' : 'Talha Muammar',
    'Johaer11' : 'Johaer Mahtab',
    'khalid_hasan_001' : 'Khalid Hasan',
    'tayhan87' : 'Tayhan Hossain',
    'promi_nh' : 'Nurjahan Bint Hamid',
    'birjis_afroz' : 'Birjis Afroz Jalil',
    'defiant_dude' : 'Md. Raheem ul islam',
    'e_e_la_hi' : 'Taufiq E Elahi',
    'Cicada2023' : 'MD. FARHAN',
    'mahir005' : 'Mahir Morshed',
    'rmia46' : 'Roman Mia',
    'atikAkabr' : 'Mohd Atik Akbar Rahat',
    'farhan03' : 'Farhan Farooq Famim',
    'tanvir_chowdhury' : 'Mohammad Tanvir Chowdhury',
    'barshon_218' : 'Barshon Basak',
    'thercube' : 'Rayed Riasat Rabbi',
    'euriskoEureka' : 'Bilash Das',
    'RIDI2322' : 'Meherin Ahmmed',
    'flying_neuron' : 'Sumon Das',
    'unexist_exe' : 'Rafiul Omar Rafi',
    'taslim1708' : 'Taslim Hossain',
    'raf66' : 'Rafee Maisoon',
    'so_what_' : 'Sowad Hossain',
    'roudrapcraker' : 'Tanvir Ahammed Roudra',
    'far_hana' : 'Farhana Akter',
    'sumayer' : 'Sumayer Khan Sajid',
    'faiyad_hossain' : 'Faiyad Hossain',
    'ksahib' : 'Kazi Sahib',
    'mahmud1319' : 'Md. Mehedi Hasan',
    'faiboi' : 'Faiyad Tanjeem Hoque',
    'awwasee' : 'Abrar Wahid Wasee',
    'kabirhosen' : 'Md. Kabir Hosen',
    'ahsanul7haque' : 'Ahsanul Haque',
    'technobyte' : 'Yousra Amin',
    'samiul223' : 'Samiul Ahmed',
    'OsamaNadeem' : 'Osama Nadeem',
    'hell37' : 'Mir Mutasim Hossain',
    'shahriar_rakib' : 'Md.Shahriar Rakib Rabbi',
    'roids' : 'Ahmed Ishmam',
    'nur35982' : 'Md. Nurnobi Islam',
    'nabila07' : 'Nabila Yesmin',
    'tamjid07' : 'Tamjid Islam',
    'sumyea_choudhury' : 'Sumyea Choudhury',
    'JINSAKAI121' : 'Shahriar Kamal',
    'turabirahman' : 'Turabi Rahman',
    'rayeedaabir' : 'Rayeed Aabir Ahsan',
    'Ffk79' : 'Fahim Farhad Khan',
    'MashhaqueRafiya' : 'Mashrafe haque',
    'ashiqiscoding' : 'HM Ashiqur Rahman',
    'MH_Jobayer' : 'Mahmodul Hasan Jobayer',
    'ShafkatxSharif' : 'Shafkat',
    'Arnob296' : 'Arnob Halder',
    'iamajmunna' : 'Assaduzzaman Munna',
    'mijan_3' : 'Mijanur Rahman',
    'abhishek_kaisar' : 'Abhishek Kaisar Abhoy',
    'ishzaz_asif' : 'Md Ishzaz Asif Rafid',
    'nafis_kamal' : 'Shah Muhammad Nafis Kamal',
    'Asadullah_Khalid' : 'Syed Asadullah Bin Omar',
    'muntasir_shawon' : 'AKM Muntasir Uddin Shawon',
    'pree_tasha' : 'Naashrah Naashidin Preetasha',
    'Drag375' : 'Atahar Hossain',
    'simkiii' : 'Umme Jahara Simki',
    'nafeesishtiaq' : 'Nafees Ishtiaq',
    'thecrazyscorp' : 'Faheema Shaheed Tamanna',
    'sowrov_007' : 'Md. Shahadat Hossain',
    'Mashrur_fardin97' : 'Mashrur Fardin',
    'nafismuktashid' : 'Md. Nafis Muktashid Arpon',
    'mdsiwom' : 'Md Siwom Chowdhury',
    'shamiul01' : 'Md. Shamiul Alam',
    'ahtaj_imty_' : 'Ahtaj Jahan Imty',
    'abdullahxsalim' : 'Abdullah Salim',
    'rkchamp' : 'Khan Rumman Ibne Reza',
    'sazim' : 'Sazim Rahman Siam',
    'Sohailk' : 'Sohail Kabir',
    'zidankhan': 'Md Zidan Khan',
    'Cursed_Child' : 'Md Ataur Rahman Ahad',
    'Munshi': 'Sakib Uz Zaman',
    'biswas2002': 'Azim Biswas’s Tazbee',
    'md_yasir_arafat': 'Md Yasir Arafat',
}

const ELIGIBILITY = {
	require: true, 
	target: 80.00, // %
}

const ELIMINATION = {
    active: false,
    target: 15,
}

const contests = {
  611667: ["Indi1", 8, 1],
  611807: ["Week1", 26, 1],
  613107: ["Indi2", 6, 1],
  613268: ["Week2", 26, 1],
  614681: ["Indi3", 7, 1],
  614684: ["Week3", 26, 1.5],
  616166: ["Indi4", 8, 1],
  616420: ["Week4", 20, 1.5],
  617626: ["Indi5", 8, 1],
  618019: ["Week5", 26, 2],
  619255: ["Indi6", 8, 1],
  619472: ["Week6", 36, 3],
  621856: ["Week 7", 26, 4],
  623119: ["LightOJ", 41, 1],
};

